### ISSUE TITLE
The Compute service was unable to access 

### ISSUE THREAD

**Issue by MrityunjayKumar123** [sassoftware/restaf-uidemos#11]
The Compute service was unable to access the specified service or server.
EOF
Error code: 5800

**Comment by MrityunjayKumar123** [comment]
Can pls help why compute server timed out and jobs getting failed.

**Comment by devaKumaraswamy** [comment]
@MrityunjayKumar123  There is not sufficient information to see what is going on in the server? 
> Recommend you enter a ticket with SAS technical support. If you are running from a browser include the output in the browser console. You can add my name as a reference in the TS ticket. 
> Also see if you can  run a data step from SAS studio - just to make sure that the compute service is running.

**Comment by devaKumaraswamy** [comment]
On second thought: Before entering a TS ticket:
1. Which program in the restaf-uidemos example are you running?
2. do a ctrl-shift-I and send the console log.
But also make sure compute server is running by using SAS studio and submitting some sas code.

**Comment by MrityunjayKumar123** [comment]
@devaKumaraswamy , SAS Technical working on ticket we got created.. however taking much time even provided logs and everything...


Error is here - The Compute service was unable to access the specified service or server.
EOF
Error code: 5800

Can you help, this is coming in many jobs while running and failing with this reason only ..

**Comment by devaKumaraswamy** [comment]
@MrityunjayKumar123 Is this still an issue? Did TS respond?

**Comment by devaKumaraswamy** [comment]
@MrityunjayKumar123  Closing this issue since you have not responded. If it is still an issue please reopen this.

**Comment by shriramwasule** [comment]
Is this issue resolved??

**Comment by devaKumaraswamy** [comment]
@shriramwasule  I did not get any information from @MrityunjayKumar123 on the final disposition of his issue. Also since he reported it we have had multiple releases. So it is hard to say if this is relevant in the current releases.

If you are having an issue like that, please report the issue to SAS Tech Support. The error seems to point to some missing microservice on his deployment.
Also if you do not mind, share the info here also.
