### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by mschubert90** [sassoftware/restaf-uidemos#13]
I've got the same issue. I tried to disable SameSite settings but the error still occurs. Has anyone a solution to that?

Thank you!

_Originally posted by @mschubert90 in https://github.com/sassoftware/restaf-uidemos/issues/6#issuecomment-1142288493_

**Comment by devaKumaraswamy** [comment]
You are better off using the SameSite.  It is less headache and will keep browsers happy. You must also set the proper values using SAS Environment Manager. See this. link https://github.com/sassoftware/restaf/wiki/usefulTips.

Also if your site is still using the sas signed certificate you need to set this before running the app
set NODE_TLS_REJECT_UNAUTHORIZED=0
I will enter a ticket on myself to set the node_tls-option as part of the npm start - will make life a bit easier. But until then you have to set the node option manually or thru your own script

**Comment by mschubert90** [comment]
I guess changing the values in SAS Environment Manager will do the job. Thank you for the quick reply.

**Comment by mschubert90** [comment]
Hello Deva,

changing the values in SAS Environment Manager indeed solved the problem. Now restAF is working for most of the demo functions. Unfortunately we get a CORS-Policy Error, but only for demo functions that have something to do with CAS Actions such as the Cas Table Browser. Listing the Cas Servers on the other hand is working...
![restAF Error](https://user-images.githubusercontent.com/98527783/172825580-223bc3ab-9806-4883-b7b6-f3bf573017b3.png)
We already changed the CORS-Settings in SAS Environment Manager and restartet our SAS Viya system. The error still occurs and only for cas action API-functions. Do you have any idea why this occurs?

Thank you!

**Comment by devaKumaraswamy** [comment]
@mschubert90  Closing this issue since the follow-up problem is covered by issue #15(which is still open).
