### ISSUE TITLE
CORS-Policy Error for CAS Actions

### ISSUE THREAD

**Issue by mschubert90** [sassoftware/restaf-uidemos#14]
Hello Deva,

changing the values in SAS Environment Manager indeed solved the problem. Now restAF is working for most of the demo functions. Unfortunately we get a CORS-Policy Error, but only for demo functions that have something to do with CAS Actions such as the Cas Table Browser. Listing the Cas Servers on the other hand is working...
![restAF Error](https://user-images.githubusercontent.com/98527783/172825580-223bc3ab-9806-4883-b7b6-f3bf573017b3.png)
We already changed the CORS-Settings in SAS Environment Manager and restartet our SAS Viya system. The error still occurs and only for cas action API-functions. Do you have any idea why this occurs?

Thank you!

_Originally posted by @mschubert90 in https://github.com/sassoftware/restaf-uidemos/issues/13#issuecomment-1150949193_

**Comment by devaKumaraswamy** [comment]
Unfortunately this bug was introduced into Viya CAS REST API, while fixing some security issue related to CSRF. This is fixed in the stable release coming out this month. (2022.1.2)
Sorry for the inconvenience.
Deva
