### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/restaf-uidemos#2]
I set the env file with oauth=NO. After starting node, I am propted with the initial config page where I put viya url, client id and secret. Then I get redirected to SASLogon. I input my credential, but after that I get "Invalid request: A redirect_uri can only be used by implicit or authorization_code grant types."

What is wrong?

**Comment by devaKumaraswamy** [comment]
Your clientid is probaby a password grant.

**Comment by devaKumaraswamy** [comment]
Due to my tardiness I missed this issue. Please reopen if my response above does not solve the issue.
