### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by chulgyu100** [sassoftware/restaf-uidemos#6]
I tried to access to app, but I got the below error.

http://localhost:8080/viyaapp?code=GDz27GOInZ&state=SD5TWBZICn-CuBZgXT81d1&refresh=1
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

![rest_error](https://user-images.githubusercontent.com/56418652/89016250-66e12980-d353-11ea-9c29-912b8dfbbc4f.jpg)

Would you like to help me for this error?

Thanks

**Comment by devaKumaraswamy** [comment]
This seems related to the latest behavior of  the latest browser(chrome) based on SAMESITE settings. I am actually in the middle of looking into it. I can make it work if the restaf-uidemos is brought up with ssl. But before I ask everyone to start using certificates let me check some more and send a note. 

Just to help me can you share some information:

1. Is your Viya running with ssl? i.e you are invoking Viya with https:// and not http - are you able to bring up SAS Viya on your browser with http://yourviyaserver? or with https://yourviyaserver?

Thanks...
Deva

**Comment by chulgyu100** [comment]
yes. My viya server is ssl-enabled.
Thansks,
chulgyu

**Comment by devaKumaraswamy** [comment]
I have not had a chance to debug all known scenarios yet but this is my preliminary finding with the new Chrome
The SAMESITE cookie options is the cause of this issue - note that this is NOT a browser issue but users are now required to do all the right things.

For a quick fix( which is basically defeating the purpose of the new security provided the SAMESITE option) you can go to chrome://flags and set **SameSite by default cookies** to disabled. You might also have to disable the Cookies without **SameSite must be secure** but not totally sure - I see some strange behavior so just noting it here for future reference.

More notes: 
1. If you set VIYA_SERVER=https://...    you will get a 500 unless you start restaf-uidemos also with ssl enabled.  To run with ssl enabled see [this](https://github.com/sassoftware/restaf-server/wiki/tls)

2. If you can use VIYA_SERVER=http://...    then disabling the options I mentioned earlier should(might?) work.

On Monday I will do some further testing and post a more detailed response.

Sidebar: I also see some different behavior if I am accessing the server via VPN - but is probably something in my setup.

**Comment by devaKumaraswamy** [comment]
Have not heard back from user

**Comment by mschubert90** [comment]
I've got the same issue. I tried to disable SameSite settings but the error still occurs. Has anyone a solution to that?

Thank you!
