### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by mehtaanirudh** [sassoftware/restaf-uidemos#7]
In the install instructions the code snippet `git clone https://sassoftware/restaf-uidemos` should be changed to `git clone https://github.com/sassoftware/restaf-uidemos`

**Comment by devaKumaraswamy** [comment]
@mehtaanirudh Thanks for pointing it out. Will fix it shortly. Cheers... Deva

**Comment by devaKumaraswamy** [comment]
duplicate of #8
